## YAML Template.
---
multitenancy:
  mtapp:
    master:
      datasource:
        url: jdbc:mysql://127.0.0.1:3306/master_db?useSSL=false
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
        connectionTimeout: 20000
        maxPoolSize: 250
        idleTimeout: 300000
        minIdle: 5
        poolName: masterdb-connection-pool